export const CREATE_GAME_START = 'CREATE_GAME_START';
export const CREATE_GAME_SUCCESS = 'CREATE_GAME_SUCCESS';
export const CREATE_GAME_ERROR = 'CREATE_GAME_ERROR';

export const LOADING_START = 'LOADING_START';
export const LOADING_END = 'LOADING_END';

export const LOGOUT = 'LOGOUT';
export const RESTORE_SESSION_START = 'RESTORE_SESSION_START';
export const RESTORE_SESSION_SUCCESS = 'RESTORE_SESSION_SUCCESS';
export const RESTORE_SESSION_ERROR = 'RESTORE_SESSION_ERROR';

export const FB_LOGIN_START = 'FB_LOGIN_START';
export const FB_LOGIN_SUCCESS = 'FB_LOGIN_SUCCESS';
export const FB_LOGIN_ERROR = 'FB_LOGIN_ERROR';

export const GOOGLE_LOGIN_START = 'GOOGLE_LOGIN_START';
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_ERROR = 'GOOGLE_LOGIN_ERROR';
